[package]
name = "ccadb-csv"
version = "0.2.0"
edition = "2021"
license = "MPL-2.0"
description = "Thin wrappers around Common CA Database (CCADB) CSV report content."
repository = "https://github.com/cpu/ccadb-utils"
keywords = ["ccadb", "pki", "tls"]

[dependencies]
csv = "1.3.0"
serde = { version = "1.0.189", features = ["derive"] }
