[package]
name = "ccadb-csv-fetch"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
description = "Utility for downloading CSV reports from the Common CA Database (CCADB)."
repository = "https://github.com/cpu/ccadb-utils"
keywords = ["ccadb", "pki", "tls"]

[dependencies]
ureq = { version = "2.6.2", default-features = false, features = [ "tls", "rustls" ] }
rustls = "0.21.5"
rustls-webpki = "0.101.2"
indicatif = "0.17.3"
ccadb-csv = { path = "../ccadb-csv", version = "0.1.0"}
